const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=f=>fs.readFileSync(path.join(root,f),'utf8');
const context={module:{exports:{}},console};vm.createContext(context);vm.runInContext(source('wealth-planning-models.js'),context);const m=context.module.exports;
// Independent monthly recurrence verifies withdrawal timing and exact final months.
for(const p of [0,100,10000,750000])for(const spend of [0,1200,75000])for(const r of [-.2,0,.04]){
 const actual=m.fundedMonths(p,spend,r);if(spend===0){assert.equal(actual,Infinity);continue;}
 const rate=Math.pow(1+r,1/12)-1;let balance=p,count=0;while(count<5000){const next=balance*(1+rate)-spend/12;if(next < -1e-7)break;balance=Math.max(0,next);count++;}if(count<5000)assert.equal(actual,count);else assert(actual===Infinity||actual>=5000);
}
assert.equal(m.fundedMonths(1200,1200,0),12);assert.equal(m.fireYears(1000000,0,900000,.04),0);assert.equal(m.fireYears(500000,0,1000000,0),Infinity);assert.equal(m.fireYears(500000,0,1000000,.04),18);assert.equal(m.fireYears(50000,0,100000,-.02),Infinity);assert.equal(m.fireYears(0,10000,100000,0),10);assert(Math.abs(m.futureValue(0,100,2,.1,true)-231)<1e-10);
for(const r of [-.05,0,.05]){const c=m.savingsRequired(10000,100000,10,r);assert(Math.abs(m.futureValue(10000,c,10,r)-100000)<1e-7);}
assert.throws(()=>m.fundedMonths(100,-1,0));assert.throws(()=>m.futureValue(100,0,2,-1));
function inline(file,needle){const chunks=[...source(file).matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(a=>a[1]);return chunks.find(s=>s.includes(needle));}
function fakeDom(values={}){const elements=new Map();const listeners={};function get(id){if(!elements.has(id))elements.set(id,{value:String(values[id]??''),style:{},textContent:'',innerText:'',innerHTML:'',classList:{add(){},remove(){},toggle(){}},reportValidity(){return true;},addEventListener(event,callback){listeners[id+':'+event]=callback;},focus(){},scrollIntoView(){},appendChild(){}});return elements.get(id);}return {elements,listeners,document:{getElementById:get,addEventListener(){},querySelectorAll(){return[];}},get};}
const rank=fakeDom(),rankContext={...rank,window:{},console};vm.createContext(rankContext);vm.runInContext(inline('calculator-embed.html','function calculateWealthPosition'),rankContext);assert.equal(rankContext.calculateWealthPosition(0).rankLow,2226000001);assert.equal(rankContext.calculateWealthPosition(10000).rank,2226000000);assert.equal(rankContext.calculateWealthPosition(100000).rank,646000000);
// Run the actual FIRE UI function, not a mirrored implementation.
const fire=fakeDom({netWorth:500000,annualSavings:0,annualExpenses:40000,swr:.04,realReturn:.04,currentAge:40});const fc={...fire,WealthPlanning:m};vm.createContext(fc);vm.runInContext(source('wealth-planning-models.js'),fc);vm.runInContext(inline('fire_timeline.html','function runFire'),fc);assert.equal(fire.get('yearsToFire').innerText,'18 years');fire.get('realReturn').value='0';fc.runFire();assert.equal(fire.get('yearsToFire').innerText,'Not reached');assert.equal(fire.get('projectedNW').innerText,'—');fire.get('netWorth').value='1000000';fc.runFire();assert.equal(fire.get('yearsToFire').innerText,'0 years');
// Whole-dollar published bins must include amounts near adjacent tail boundaries.
const hh=fakeDom({householdWealth:999999.5,benchmark:'all'});const hc={...hh,window:{},Intl,console};vm.createContext(hc);vm.runInContext(inline('us-household-wealth.html','const BINS'),hc);
const key=vm.runInContext('Object.keys(BENCHMARKS)[0]',hc);hh.get('benchmark').value=key;
for(const value of [-100,0,.5,4999.5,499999.5,500000,999999.4,999999.5,1000000,2499999.5,1e12]){hh.get('householdWealth').value=String(value);assert.equal(hc.calculateHousehold(),true);assert(!hh.get('rankRange').textContent.includes('NaN'));}
// Exercise the existing simulation at zero volatility: all quantiles equal its constant-return path.
const wc={window:{addEventListener(){}},document:{addEventListener(){}},console};vm.createContext(wc);vm.runInContext(source('assets/wealth-horizon.js'),wc);const input={starting:100000,contribution:12000,years:5,returnRate:0,volatility:0,inflation:0,fees:0,taxDrag:0,contributionGrowth:0};const wr=wc.window.WealthHorizon.calculate(input);assert(Math.abs(wr.nominal-160000)<1e-7);for(const row of wr.rows){assert(Math.abs(row.p10-row.real)<1e-6);assert(Math.abs(row.p90-row.real)<1e-6);}
// Exercise the historical calculator validator inside its original closure.
const hist={console};vm.createContext(hist);vm.runInContext(source('assets/historical-return-windows.js').replace('  init();','  globalThis.historicalTest={validateCalculator,annualized,windowsFor,setData(value){data=value;}};'),hist);const base={age:40,targetAge:60,balance:100000,monthly:100,stocks:60,bonds:30};assert.equal(hist.historicalTest.validateCalculator(base),'');for(const weights of [{stocks:-1},{bonds:NaN},{stocks:Infinity},{stocks:90,bonds:20}])assert.notEqual(hist.historicalTest.validateCalculator({...base,...weights}),'');
// The new national runway selects actual data fields and sane positive ratios.
const ppw={window:{}};vm.createContext(ppw);vm.runInContext(source('ppw-real-data.js'),ppw);assert(ppw.window.PPW_REAL_DATA.countries.length>=160);for(const row of ppw.window.PPW_REAL_DATA.countries)assert(Number.isFinite(row.price_level_usa100)&&row.price_level_usa100>0&&Number.isInteger(row.year));
console.log('PASS: Wealth calculator timing, boundaries, source-field wiring, and simulation regressions');
